name: Build and Deploy to Firebase
on:
  release:
    types: [created]

env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  CI: false
jobs:
  build_and_deploy:
    name: Build WebApp and deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn global add firebase-tools
          export PATH="$(yarn global bin):$PATH"

      - name: Build WebApp
        run: yarn build-storybook

      - name: Deploy
        run: firebase deploy --only hosting --token $FIREBASE_TOKEN
