name: Build and Deploy to Firebase
on:
  release:
    types: [created]

env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  CI: false
jobs:
  build_and_deploy:
    name: Build WebApp and deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: |
          npm install
          npm install firebase-tools -g

      - name: Build WebApp
        run: npm run build

      - name: Deploy
        run: firebase deploy --only hosting --token $FIREBASE_TOKEN
