name: Publish NPM package on release
on:
  release:
    types: [created]

jobs:
  build:
    name: Setup Nodejs and publish the package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn

      - name: Publish the package
        run: yarn publish --frozen-lockfile --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
